language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install PyYAML argparse
  - pip install nose coverage
# command to run tests
script:
  - nosetests -s
notifications:
  email: false
