apr:
  arch: apr apr-util
  cygwin: libapr1 libaprutil1
  debian: libapr1-dev libaprutil1-dev
  fedora: apr-devel apr-util
  freebsd: builtin
  gentoo: dev-libs/apr dev-libs/apr-util
  macports: apr apr-util
  opensuse: libapr1 libapr-util1
  osxbrew:
    homebrew: {packages: ''}
  rhel: apr-devel apr-util
  ubuntu: libapr1-dev libaprutil1-dev
assimp:
  debian:
    source: {md5sum: d5137302d8f00241ee10e623b97f9d22, uri: 'https://kforge.ros.org/rosrelease/viewvc/sourcedeps/assimp/assimp-2.0.86-1.rdmanifest'}
  osxbrew:
    homebrew:
      packages: [assimp]
  ubuntu:
    apt:
      packages: [assimp-dev]
atlas:
  arch: ''
  debian: libatlas-base-dev
  fedora: atlas-devel
  gentoo: atlas
  macports: atlas
  osxbrew:
    homebrew: {packages: ''}
  ubuntu: libatlas-base-dev
autoconf:
  arch: autoconf
  debian: autoconf
  fedora: autoconf
  freebsd: autoconf213 autoconf268
  gentoo: sys-devel/autoconf
  macports: autoconf
  opensuse: autoconf
  osxbrew:
    homebrew: {packages: ''}
  rhel: autoconf
  ubuntu: autoconf
automake:
  arch: automake
  debian: automake
  fedora: automake
  freebsd: automake14 automake111
  gentoo: sys-devel/automake
  macports: automake
  opensuse: automake
  osxbrew:
    homebrew: {packages: ''}
  rhel: automake
  ubuntu: automake
bazaar:
  debian: bzr
  fedora: bazaar
  freebsd: bazaar
  gentoo: dev-vcs/bzr
  macports: bazaar
  opensuse: bzr
  osxbrew:
    homebrew:
      packages: [bazaar]
  ubuntu: bzr
boost:
  arch: boost
  cygwin: libboost-devel libboost1.40
  debian: {lenny: "if [ ! -f /opt/ros/lib/libboost_date_time-gcc43-mt*-1_37.a ] ;\
      \ then\n  mkdir -p ~/ros/ros-deps\n  cd ~/ros/ros-deps\n  wget --tries=10 http://pr.willowgarage.com/downloads/boost_1_37_0.tar.gz\n\
      \  tar xzf boost_1_37_0.tar.gz\n  cd boost_1_37_0\n  ./configure --prefix=/opt/ros\n\
      \  make\n  sudo make install\nfi\n", squeeze: libboost1.42-all-dev}
  fedora: boost-devel
  freebsd: boost-python-libs
  gentoo: dev-libs/boost
  macports: boost
  opensuse: boost-devel
  osxbrew:
    homebrew:
      packages: [boost]
  rhel: boost-devel
  ubuntu:
    lucid:
      apt:
        packages: [libboost1.40-all-dev]
    maverick:
      apt:
        packages: [libboost1.42-all-dev]
    natty:
      apt:
        packages: [libboost1.42-all-dev]
    oneiric:
      apt:
        packages: [libboost1.46-all-dev]
bzip2:
  arch: bzip2
  cygwin: bzip2
  debian: libbz2-dev
  fedora: bzip2-devel
  freebsd: bzip2
  gentoo: app-arch/bzip2
  macports: bzip2
  opensuse: libbz2-devel
  osxbrew:
    homebrew: {packages: ''}
  rhel: bzip2-devel
  ubuntu: libbz2-dev
checkinstall:
  debian:
    apt:
      packages: [checkinstall]
  osxbrew:
    homebrew: {packages: ''}
  ubuntu:
    apt:
      packages: [checkinstall]
cppunit:
  arch: cppunit
  debian: libcppunit-dev
  fedora: cppunit-devel
  freebsd: cppunit
  gentoo: dev-util/cppunit
  macports: cppunit
  opensuse: libcppunit-devel
  osxbrew:
    homebrew:
      args: [--universal]
      packages: [cppunit]
  rhel: cppunit-devel
  ubuntu: libcppunit-dev
curl:
  arch: curl
  debian: libcurl4-openssl-dev
  fedora: libcurl-devel
  freebsd: curl
  gentoo: net-misc/curl
  macports: curl
  opensuse: libcurl-devel
  osxbrew:
    homebrew: {packages: ''}
  ubuntu: libcurl4-openssl-dev
doxygen:
  arch: doxygen
  debian: doxygen
  fedora: doxygen
  freebsd: doxygen
  gentoo: app-doc/doxygen
  macports: doxygen
  osxbrew:
    lion:
      homebrew:
        packages: [doxygen]
  rhel: doxygen
  ubuntu: doxygen
eigen:
  debian:
    source: {md5sum: 941db2fbb09d80c28426d335022fad95, uri: 'https://kforge.ros.org/rosrelease/viewvc/sourcedeps/eigen/eigen-3.0.1-1.rdmanifest'}
  gentoo: '>=dev-cpp/eigen-3'
  osxbrew:
    homebrew:
      packages: [eigen]
  ubuntu:
    apt:
      packages: [libeigen3-dev]
epydoc:
  debian: python-epydoc
  fedora: epydoc
  freebsd: epydoc
  gentoo: dev-python/epydoc
  macports: py26-epydoc
  osxbrew:
    lion:
      pip:
        packages: [epydoc]
  ubuntu: python-epydoc
festival: {arch: festival festival-kallpc16k, debian: festival festvox-kallpc16k,
  ubuntu: festival festvox-kallpc16k}
ffmpeg:
  arch: ffmpeg
  debian: libavcodec-dev libavformat-dev libavutil-dev libswscale-dev
  gentoo: ffmpeg
  macports: ffmpeg
  osxbrew:
    homebrew:
      packages: [ffmpeg]
  ubuntu: libavcodec-dev libavformat-dev libavutil-dev libswscale-dev
fltk:
  arch: fltk
  debian: libfltk1.1-dev
  fedora: fltk-devel
  freebsd: fltk
  gentoo: =x11-libs/fltk-1*
  macports: fltk
  opensuse: fltk-devel
  osxbrew:
    homebrew:
      packages: [fltk]
  ubuntu: libfltk1.1-dev
gfortran:
  osxbrew:
    homebrew:
      packages: [gfortran]
git:
  debian: git-core
  fedora: git
  freebsd: git
  gentoo: dev-vcs/git
  macports: git-core
  opensuse: git-core
  osxbrew:
    homebrew:
      packages: [git]
  ubuntu: git-core
graphicsmagick:
  arch: graphicsmagick
  debian: libgraphicsmagick++1-dev
  gentoo: imagemagick
  macports: GraphicsMagick
  osxbrew:
    homebrew:
      packages: [graphicsmagick]
  ubuntu: libgraphicsmagick++1-dev
graphviz:
  arch: graphviz
  debian: graphviz
  fedora: graphviz
  freebsd: graphviz
  gentoo: media-gfx/graphviz
  macports: graphviz
  opensuse: graphviz
  osxbrew:
    homebrew:
      options: []
      packages: [graphviz]
  rhel: graphviz
  ubuntu: graphviz
gtest:
  debian: libgtest-dev
  fedora: gtest-devel
  freebsd: googletest
  gentoo: dev-util/gtest
  macports: google-test
  opensuse: gtest-devel
  osxbrew:
    homebrew:
      options: [--universal]
      packages: [gtest]
  ubuntu: libgtest-dev
gtk2:
  arch: gtk2
  debian: libgtk2.0-dev
  fedora: gtk2-devel
  freebsd: gtk20
  gentoo: x11-libs/gtk+
  macports: gtk2
  opensuse: gtk2-devel
  osxbrew:
    homebrew:
      packages: [gtk+]
  rhel: gtk2-devel
  ubuntu: libgtk2.0-dev
intltool: {fedora: intltool, freebsd: intltool, gentoo: dev-util/intltool, opensuse: intltool,
  ubuntu: intltool}
jasper:
  arch: jasper
  debian: libjasper-dev
  gentoo: jasper
  macports: jasper
  osxbrew:
    homebrew:
      args: [--universal]
      packages: [jasper]
  ubuntu: libjasper-dev
libstdc++5: {debian: libstdc++5, freebsd: builtin, opensuse: libstdc++33, ubuntu: libstdc++5}
libtool:
  arch: libtool
  debian: {lenny: libtool libltdl3-dev, squeeze: libtool libltdl-dev}
  fedora: libtool libtool-ltdl-devel
  freebsd: libtool
  gentoo: sys-devel/libtool
  macports: libtool
  opensuse: libtool libltdl3
  osxbrew:
    homebrew: {packages: ''}
  rhel: libtool libtool-ltdl-devel
  ubuntu:
    apt:
      packages: [libtool, libltdl-dev]
libxaw:
  arch: libxaw
  debian: libxaw7-dev
  fedora: libXaw-devel
  freebsd: libXaw
  gentoo: x11-libs/libXaw
  macports: xorg-libXaw
  opensuse: xorg-x11-devel
  osxbrew:
    homebrew: {packages: ''}
  rhel: libXaw-devel
  ubuntu: libxaw7-dev
libxext:
  arch: libxext
  debian: libxext-dev
  fedora: libXext-devel
  freebsd: libXext
  gentoo: x11-libs/libXext
  macports: xorg-libXext
  opensuse: xorg-x11-libXext-devel
  osxbrew:
    homebrew: {packages: ''}
  rhel: libXext-devel
  ubuntu: libxext-dev
libxml2:
  arch: libxml2
  debian: libxml2-dev
  fedora: libxml2-devel
  freebsd: libxml2
  gentoo: dev-libs/libxml2
  macports: libxml2
  opensuse: libxml2-devel
  osxbrew:
    homebrew:
      packages: [libxml2]
  ubuntu: libxml2-dev
libxxf86vm:
  arch: libxxf86vm
  debian: libxxf86vm-dev
  fedora: libXxf86vm-devel
  freebsd: libXxf86vm
  gentoo: x11-libs/libXxf86vm
  macports: xorg-libXxf86vm
  opensuse: xorg-x11-devel
  osxbrew:
    homebrew: {packages: ''}
  rhel: libXxf86vm-devel
  ubuntu: libxxf86vm-dev
log4cxx:
  arch: 'if ! pacman -Q log4cxx; then yaourt -S log4cxx; fi

    '
  cygwin: liblog4cxx-devel
  debian: {lenny: "if [ ! -f /opt/ros/lib/liblog4cxx.so.10 ] ; then\n  mkdir -p ~/ros/ros-deps\n\
      \  cd ~/ros/ros-deps\n  wget --tries=10 http://pr.willowgarage.com/downloads/apache-log4cxx-0.10.0-wg_patched.tar.gz\n\
      \  tar xzf apache-log4cxx-0.10.0-wg_patched.tar.gz\n  cd apache-log4cxx-0.10.0\n\
      \  ./configure --prefix=/opt/ros\n  make\n  sudo make install\nfi\n", squeeze: liblog4cxx10-dev}
  fedora: log4cxx-devel
  freebsd: log4cxx
  gentoo: dev-libs/log4cxx
  macports: log4cxx
  opensuse: log4cxx-devel
  osxbrew:
    homebrew:
      args: [--universal]
      packages: [log4cxx]
  rhel: log4cxx-devel
  ubuntu: liblog4cxx10-dev
mercurial:
  debian: mercurial
  fedora: mercurial
  freebsd: mercurial
  gentoo: dev-vcs/mercurial
  macports: mercurial
  opensuse: mercurial
  osxbrew:
    pip:
      packages: [mercurial]
  ubuntu: mercurial
opengl:
  arch: mesa
  debian: libgl1-mesa-dev libglu1-mesa-dev
  fedora: mesa-libGL-devel mesa-libGLU-devel
  freebsd: mesagl-mangled
  gentoo: media-libs/mesa
  macports: mesa
  opensuse: Mesa-devel
  osxbrew:
    homebrew: {packages: ''}
  rhel: mesa-libGL-devel mesa-libGLU-devel
  ubuntu: libgl1-mesa-dev libglu1-mesa-dev
pkg-config:
  arch: pkg-config
  cygwin: pkg-config
  debian: pkg-config
  fedora: pkgconfig
  freebsd: pkg-config
  gentoo: dev-util/pkgconfig
  macports: pkgconfig
  opensuse: pkg-config
  osxbrew:
    homebrew:
      packages: [pkg-config]
  rhel: pkgconfig
  ubuntu: pkg-config
python-sip4:
  arch: sip
  debian: python-sip4-dev sip4
  gentoo: dev-python/sip
  macports: py25-sip
  osxbrew:
    homebrew:
      packages: [sip]
  ubuntu: python-sip4-dev sip4
python-sphinx:
  debian: python-sphinx
  fedora: python-sphinx
  freebsd: py27-sphinx
  macports: py26-sphinx
  osxbrew:
    lion:
      pip:
        packages: [Sphinx]
  ubuntu: python-sphinx
qt4:
  arch: qt
  debian: libqt4-dev qt4-dev-tools
  fedora: qt-devel
  freebsd: qt4-corelib
  gentoo: '>=x11-libs/qt-core-4'
  macports: qt4-mac
  opensuse: libqt4-devel
  osxbrew:
    homebrew:
      options: [--universal]
      packages: [qt]
  ubuntu: libqt4-dev qt4-dev-tools
scons:
  arch: scons
  debian: scons
  fedora: scons
  freebsd: scons
  gentoo: dev-util/scons
  macports: scons
  opensuse: scons
  osxbrew:
    homebrew: {packages: ''}
  ubuntu: scons
subversion:
  debian: subversion
  fedora: subversion
  freebsd: subversion
  gentoo: dev-vcs/subversion
  macports: subversion
  opensuse: subversion
  osxbrew:
    homebrew:
      packages: [subversion]
  ubuntu: subversion
tinyxml:
  debian: libtinyxml-dev
  fedora: tinyxml-devel
  osxbrew:
    homebrew:
      formula_uri: https://kforge.ros.org/rososx/homebrew/file/tip/electric/tinyxml.rb
      packages: [tinyxml]
  ubuntu: libtinyxml-dev
unzip:
  arch: unzip
  debian: unzip
  fedora: unzip
  freebsd: unzip
  gentoo: app-arch/unzip
  macports: unzip
  opensuse: unzip
  osxbrew:
    homebrew: {packages: ''}
  rhel: unzip
  ubuntu: unzip
wxpython:
  arch: wxpython
  centos: wxPython-devel
  debian: python-wxgtk2.8
  fedora: wxPython-devel
  freebsd: py27-wxPython
  gentoo: dev-python/wxpython
  macports: py26-wxpython py26-gobject py26-gtk py26-cairo
  opensuse: python-wxGTK
  osxbrew:
    source: {md5sum: 4fdb30e1abfb4a36a4c5d9efc48049c4, uri: 'http://mirror.ausparc.com/ros/sourcedeps/wxPython.rdmanifest'}
  rhel: wxPython-devel
  ubuntu: python-wxgtk2.8
wxwidgets:
  arch: wxgtk
  debian: libwxgtk2.8-dev
  fedora: wxGTK-devel
  freebsd: wxgtk2
  gentoo: x11-libs/wxGTK
  macports: wxWidgets-python
  opensuse: wxGTK-devel
  osxbrew:
    homebrew:
      depends: [wxpython]
  rhel: wxGTK-devel
  ubuntu: libwxgtk2.8-dev
yaml:
  fedora: libyaml-devel
  osxbrew:
    homebrew:
      options: [--universal]
      packages: [libyaml]
  ubuntu: libyaml-dev
yaml-cpp:
  debian:
    source: {md5sum: f7fb81fd4a2fbd5022daa7686e816359, uri: 'https://kforge.ros.org/rosrelease/viewvc/sourcedeps/yaml-cpp/yaml-cpp-0.2.5.rdmanifest'}
  osxbrew:
    homebrew:
      depends: [yaml]
      packages: [yaml-cpp]
  ubuntu:
    apt:
      packages: [yaml-cpp0.2.6-dev]
zlib:
  arch: zlib
  cygwin: zlib
  debian: zlib1g-dev
  fedora: zlib-devel
  freebsd: builtin
  gentoo: sys-libs/zlib
  macports: zlib
  opensuse: zlib-devel
  osxbrew:
    homebrew: {packages: ''}
  rhel: zlib-devel
  ubuntu: zlib1g-dev
zziplib:
  arch: zziplib
  debian: libzzip-0-13 libzzip-dev
  fedora: zziplib-devel
  freebsd: zziplib
  gentoo: dev-libs/zziplib
  macports: libzzip
  opensuse: zziplib-devel
  osxbrew:
    homebrew:
      packages: [libzzip]
  rhel: zziplib-devel
  ubuntu: libzzip-0-13 libzzip-dev
